import type { SimulationData } from '@/types/simulation'

// ========== HELPERS ==========

function esc(val: unknown): string {
  const s = String(val ?? '').replace(/"/g, '""')
  return `"${s}"`
}

function downloadBlob(content: string, filename: string, type: string) {
  const blob = new Blob([content], { type })
  const url = URL.createObjectURL(blob)
  const a = document.createElement('a')
  a.href = url
  a.download = filename
  a.click()
  URL.revokeObjectURL(url)
}

// ========== CSV EXPORT ==========

export function exportToCSV(data: Partial<SimulationData>): void {
  const lines: string[] = []

  // Company Info
  lines.push('COMPANY INFO')
  lines.push('Field,Value')
  lines.push(`Name,${esc(data.name)}`)
  lines.push(`Tagline,${esc(data.tagline)}`)
  lines.push(`Value Proposition,${esc(data.valueProposition)}`)
  lines.push(`Business Model,${esc(data.businessModel)}`)
  lines.push(`Verdict,${esc(data.verdict)}`)
  lines.push('')

  // Features
  if (data.features?.length) {
    lines.push('FEATURES')
    lines.push('Feature')
    data.features.forEach(f => lines.push(esc(f)))
    lines.push('')
  }

  // Competitors
  if (data.competitors?.length) {
    lines.push('COMPETITORS')
    lines.push('Name,Market Coverage,Feature Completeness,Funding,Pricing')
    data.competitors.forEach(c =>
      lines.push(`${esc(c.name)},${c.x},${c.y},${esc(c.funding)},${esc(c.pricing)}`)
    )
    lines.push('')
  }

  // Market Trends
  if (data.market?.demandTrend?.length) {
    lines.push('DEMAND TREND')
    lines.push('Year,Value')
    data.market.demandTrend.forEach(t => lines.push(`${t.year},${t.value}`))
    lines.push('')
  }

  // Workforce
  if (data.market?.workforceCapacity?.length) {
    lines.push('WORKFORCE CAPACITY')
    lines.push('City,Count')
    data.market.workforceCapacity.forEach(w => lines.push(`${esc(w.city)},${w.count}`))
    lines.push('')
  }

  // TAM/SAM/SOM
  if (data.marketExtended?.marketSize) {
    const ms = data.marketExtended.marketSize
    lines.push('MARKET SIZE')
    lines.push('Metric,Value')
    lines.push(`TAM,${ms.tam}`)
    lines.push(`SAM,${ms.sam}`)
    lines.push(`SOM,${ms.som}`)
    lines.push('')
  }

  // Strengths
  if (data.strengths?.length) {
    lines.push('STRENGTHS')
    lines.push('Title,Description,Source')
    data.strengths.forEach(s => lines.push(`${esc(s.title)},${esc(s.description)},${esc(s.source)}`))
    lines.push('')
  }

  // Risks
  if (data.risks?.length) {
    lines.push('RISKS')
    lines.push('Title,Description,Source')
    data.risks.forEach(r => lines.push(`${esc(r.title)},${esc(r.description)},${esc(r.source)}`))
    lines.push('')
  }

  // Next Steps
  if (data.nextSteps?.length) {
    lines.push('NEXT STEPS')
    lines.push('Priority,Title,Description')
    data.nextSteps.forEach(n => lines.push(`${esc(n.priority)},${esc(n.title)},${esc(n.description)}`))
    lines.push('')
  }

  const filename = `${(data.name || 'report').replace(/\s+/g, '_')}_data.csv`
  downloadBlob(lines.join('\n'), filename, 'text/csv;charset=utf-8;')
}

// ========== BOARD EXPORT (Markdown → Clipboard) ==========

export async function exportToBoard(data: Partial<SimulationData>): Promise<boolean> {
  const l: string[] = []

  l.push(`# ${data.name || 'Startup'} — Validation Report`)
  l.push(`> ${data.tagline || ''}`)
  l.push('')

  // Next Steps first (most actionable)
  if (data.nextSteps?.length) {
    l.push('## Next Steps')
    const groups: Record<string, typeof data.nextSteps> = { critical: [], important: [], helpful: [] }
    data.nextSteps.forEach(n => (groups[n.priority] || groups.helpful).push(n))

    for (const [priority, steps] of Object.entries(groups)) {
      if (steps.length === 0) continue
      l.push(`### ${priority.charAt(0).toUpperCase() + priority.slice(1)}`)
      steps.forEach(n => {
        l.push(`- [ ] **${n.title}**`)
        l.push(`  > ${n.description}`)
      })
      l.push('')
    }
  }

  // Features
  if (data.features?.length) {
    l.push('## Features to Build')
    data.features.forEach(f => l.push(`- [ ] ${f}`))
    l.push('')
  }

  // Vision
  l.push('## Vision')
  if (data.valueProposition) l.push(`**Value Proposition:** ${data.valueProposition}`)
  if (data.businessModel) l.push(`**Business Model:** ${data.businessModel}`)
  l.push('')

  // Strengths
  if (data.strengths?.length) {
    l.push('## Strengths')
    data.strengths.forEach(s => l.push(`- **${s.title}**: ${s.description}`))
    l.push('')
  }

  // Risks
  if (data.risks?.length) {
    l.push('## Risks')
    data.risks.forEach(r => l.push(`- **${r.title}**: ${r.description}`))
    l.push('')
  }

  // Verdict
  if (data.verdict) {
    l.push('## Verdict')
    l.push(data.verdict)
    l.push('')
  }

  l.push('---')
  l.push('*Generated by ShipIt*')

  try {
    await navigator.clipboard.writeText(l.join('\n'))
    return true
  } catch {
    return false
  }
}

// ========== PDF EXPORT ==========

export async function exportToPDF(data: Partial<SimulationData>, reportId: string | null): Promise<void> {
  // Dynamic imports to avoid SSR issues
  const [{ default: jsPDF }, { default: html2canvas }] = await Promise.all([
    import('jspdf'),
    import('html2canvas'),
  ])

  // Build a hidden HTML report
  const container = document.createElement('div')
  container.style.cssText = 'position:absolute;left:-9999px;width:800px;padding:48px;background:#fff;color:#111;font-family:system-ui,-apple-system,sans-serif;'

  const cyan = '#0969da'
  const green = '#1a7f37'
  const red = '#cf222e'
  const amber = '#9a6700'
  const dimText = '#656d76'

  const sectionHeader = (title: string, color = cyan) =>
    `<h2 style="font-size:15px;color:${color};border-bottom:1px solid #d0d7de;padding-bottom:6px;margin:24px 0 12px;">${title}</h2>`

  const sections: string[] = []

  // Header
  sections.push(`
    <div style="border-bottom:2px solid ${cyan};padding-bottom:16px;margin-bottom:24px;">
      <h1 style="font-size:26px;margin:0;color:${cyan};font-weight:700;">${data.name || 'Startup Report'}</h1>
      <p style="font-size:13px;margin:6px 0 0;color:${dimText};">${data.tagline || ''}</p>
      <p style="font-size:10px;margin:4px 0 0;color:#8b949e;">Generated ${new Date().toLocaleDateString('en-US', { year: 'numeric', month: 'long', day: 'numeric' })}${reportId ? ` · ID: ${reportId}` : ''}</p>
    </div>
  `)

  // Value Proposition
  if (data.valueProposition) {
    sections.push(sectionHeader('Value Proposition'))
    sections.push(`<p style="font-size:12px;line-height:1.7;margin:0;">${data.valueProposition}</p>`)
  }

  // Business Model
  if (data.businessModel) {
    sections.push(sectionHeader('Business Model'))
    sections.push(`<p style="font-size:12px;line-height:1.7;margin:0;">${data.businessModel}</p>`)
  }

  // Features
  if (data.features?.length) {
    sections.push(sectionHeader('Core Features'))
    sections.push(`<div style="display:flex;flex-wrap:wrap;gap:6px;margin-top:4px;">
      ${data.features.map(f => `<span style="font-size:11px;padding:3px 10px;background:#ddf4ff;color:${cyan};border-radius:12px;">${f}</span>`).join('')}
    </div>`)
  }

  // Competitors
  if (data.competitors?.length) {
    sections.push(sectionHeader('Competitive Landscape'))
    sections.push(`<table style="width:100%;border-collapse:collapse;font-size:11px;margin-top:4px;">
      <tr style="background:#f6f8fa;"><th style="text-align:left;padding:6px 8px;border:1px solid #d0d7de;">Name</th><th style="padding:6px 8px;border:1px solid #d0d7de;">Coverage</th><th style="padding:6px 8px;border:1px solid #d0d7de;">Features</th><th style="padding:6px 8px;border:1px solid #d0d7de;">Funding</th><th style="padding:6px 8px;border:1px solid #d0d7de;">Pricing</th></tr>
      ${data.competitors.map(c => `<tr><td style="padding:5px 8px;border:1px solid #d0d7de;font-weight:${c.name === 'YOU' ? '700' : '400'};color:${c.name === 'YOU' ? cyan : '#111'};">${c.name}</td><td style="text-align:center;padding:5px 8px;border:1px solid #d0d7de;">${c.x}</td><td style="text-align:center;padding:5px 8px;border:1px solid #d0d7de;">${c.y}</td><td style="text-align:center;padding:5px 8px;border:1px solid #d0d7de;">${c.funding}</td><td style="text-align:center;padding:5px 8px;border:1px solid #d0d7de;">${c.pricing}</td></tr>`).join('')}
    </table>`)
  }

  // Strengths
  if (data.strengths?.length) {
    sections.push(sectionHeader('Strengths', green))
    data.strengths.forEach(s => {
      sections.push(`<div style="margin-bottom:10px;">
        <div style="font-size:12px;font-weight:600;color:${green};">${s.title}</div>
        <div style="font-size:11px;line-height:1.5;color:#333;margin-top:2px;">${s.description}</div>
        <div style="font-size:9px;color:${dimText};margin-top:2px;">Source: ${s.source}</div>
      </div>`)
    })
  }

  // Risks
  if (data.risks?.length) {
    sections.push(sectionHeader('Risks', red))
    data.risks.forEach(r => {
      sections.push(`<div style="margin-bottom:10px;">
        <div style="font-size:12px;font-weight:600;color:${red};">${r.title}</div>
        <div style="font-size:11px;line-height:1.5;color:#333;margin-top:2px;">${r.description}</div>
        <div style="font-size:9px;color:${dimText};margin-top:2px;">Source: ${r.source}</div>
      </div>`)
    })
  }

  // Verdict
  if (data.verdict) {
    sections.push(sectionHeader('The Verdict'))
    sections.push(`<p style="font-size:12px;line-height:1.7;margin:0;padding:12px;background:#f6f8fa;border-left:3px solid ${cyan};border-radius:2px;">${data.verdict}</p>`)
  }

  // Next Steps
  if (data.nextSteps?.length) {
    sections.push(sectionHeader('Next Steps'))
    const priorityColor: Record<string, string> = { critical: red, important: amber, helpful: green }
    data.nextSteps.forEach(n => {
      const pc = priorityColor[n.priority] || dimText
      sections.push(`<div style="margin-bottom:8px;display:flex;gap:8px;align-items:flex-start;">
        <span style="font-size:9px;padding:1px 6px;border-radius:8px;background:${pc}15;color:${pc};border:1px solid ${pc}40;white-space:nowrap;margin-top:2px;">${n.priority}</span>
        <div>
          <div style="font-size:11px;font-weight:600;">${n.title}</div>
          <div style="font-size:10px;color:#555;line-height:1.4;">${n.description}</div>
        </div>
      </div>`)
    })
  }

  // Footer
  sections.push(`<div style="margin-top:32px;padding-top:12px;border-top:1px solid #d0d7de;text-align:center;">
    <p style="font-size:9px;color:#8b949e;margin:0;">Generated by ShipIt</p>
  </div>`)

  container.innerHTML = sections.join('')
  document.body.appendChild(container)

  const canvas = await html2canvas(container, { scale: 2, backgroundColor: '#ffffff', logging: false })
  document.body.removeChild(container)

  const pdf = new jsPDF({ orientation: 'portrait', unit: 'px', format: 'a4' })
  const pageW = pdf.internal.pageSize.getWidth()
  const pageH = pdf.internal.pageSize.getHeight()
  const imgW = pageW
  const imgH = (canvas.height * imgW) / canvas.width

  let y = 0
  pdf.addImage(canvas.toDataURL('image/png'), 'PNG', 0, y, imgW, imgH)
  let remaining = imgH - pageH

  while (remaining > 0) {
    y -= pageH
    pdf.addPage()
    pdf.addImage(canvas.toDataURL('image/png'), 'PNG', 0, y, imgW, imgH)
    remaining -= pageH
  }

  pdf.save(`${(data.name || 'report').replace(/\s+/g, '_')}.pdf`)
}
